title: Read, apply, learn
email: cortesfernandezdionisio@gmail.com
description: >-
  As I spend lots of time reading about software I want to try and share some thoughts. 
  Hopefully this will encourage me to practise more and push me to the next level.
  The main goal is to improve
baseurl: ""
url: ""
github_username:  dionisioC

markdown: kramdown
theme: minima
